/**
 * Supported cross-runtime API. Browser and server workspaces import only this
 * surface; unlisted module internals remain free to change locally.
 */
export {
  MAX_ACCOUNT_DISPLAY_NAME_LENGTH,
  MAX_ACCOUNT_EMAIL_LENGTH,
  MAX_ACCOUNT_PASSWORD_LENGTH,
  MIN_ACCOUNT_PASSWORD_LENGTH,
  type AccountUser,
} from './accountContract.js';
export {
  DEMO_ACCOUNTS,
  isDemoAccountEmail,
  type DemoAccount,
} from './demoAccounts.js';
export {
  MAX_BOARD_TITLE_LENGTH,
  truncateBoardTitle,
  unicodeScalarLength,
  type BoardInviteLink,
  type BoardMember,
  type BoardRole,
  type TrashedBoardSummary,
} from './boardContract.js';
export {
  COLLABORATION_MESSAGE_ACKNOWLEDGEMENT,
  COLLABORATION_MESSAGE_AWARENESS,
  COLLABORATION_MESSAGE_SYNC,
} from './collaborationContract.js';
export { crc32 } from './crc32.js';
export {
  DEFAULT_ELEMENT_STYLE,
  DEFAULT_EQUATION_LINE_SPACING,
  EQUATION_SOURCE_FONT_SIZE_OFFSET,
  equationSourceFontSize,
  isEquationElement,
  isFreehandElement,
  isImageElement,
  isLinearElement,
  isShapeElement,
  MAX_FREEHAND_POINTS,
  type ArrowElement,
  type BaseElement,
  type BezierSegment,
  type BoardElement,
  type ElementStyle,
  type ElementType,
  type FillStyle,
  type EquationElement,
  type FreehandElement,
  type ImageElement,
  type LineArrowheads,
  type LineElement,
  type LinearElement,
  type PathKind,
  type Point,
  type RectangleElement,
  type ShapeElement,
  type ShapeKind,
  type SplineContinuity,
  type StrokeStyle,
} from './elementSchema.js';
export {
  bezierAccuracyTargetError,
  boundsForPoints,
  boundsIntersect,
  distanceToSegment,
  elementBounds,
  enforceBezierContinuity,
  fitBezierSegments,
  fitOrthogonalSegments,
  hitTestElement,
  linePathGeometry,
  linePathPoints,
  MAX_BEZIER_FIT_SAMPLES,
  normalizeBounds,
  normalizeRectangle,
  normalizeShape,
  pointInBounds,
  polylineCubicSegments,
  sampleBezierPoints,
  screenToWorld,
  selectionBounds,
  simplifiedPointIndexes,
  strokeEndDirection,
  translateElement,
  worldToScreen,
  type AbsoluteBezierSegment,
  type BezierFitOptions,
  type Bounds,
  type Camera,
  type LinePathGeometry,
} from './geometry.js';
export {
  DEFAULT_TRAPEZOID_TOP_LEFT,
  DEFAULT_TRAPEZOID_TOP_RIGHT,
  hatchSegments,
  MAX_SHAPE_FILL_SPACING,
  MIN_SHAPE_FILL_SPACING,
  MIN_TRAPEZOID_TOP_EDGE_RATIO,
  normalizedTrapezoidTop,
  roundedPolygonCorners,
  type RoundedCorner,
  SHAPE_HATCH_ANGLE,
  SHAPE_HATCH_SPACING,
  shapeFillPolygon,
  shapeFillSegments,
  shapeHatchSpacing,
  shapeHatchStrokeWidth,
  shapePolygonPoints,
  trapezoidPoints,
} from './shapeGeometry.js';
export {
  isMixedContentDocument,
  type MixedContentDocument,
  type MixedContentRow,
  type MixedContentSpan,
  type MixedMathSpan,
  type MixedTextAttributes,
  type MixedTextSpan,
} from './mixedContent.js';
export {
  initializeYMixedContent,
  mixedContentFromYDoc,
  mixedContentFromYRoot,
  mixedContentRoot,
  reconcileYMixedContent,
  yMixedContentRows,
  yMixedContentSpans,
  yMixedContentText,
  type YMixedContentRoot,
  type YMixedContentRow,
  type YMixedContentSpan,
} from './yjsMixedContent.js';
export {
  CHALKBOARD_SCHEMA_VERSIONS,
  type ApplicationDiagnostics,
} from './schemaVersions.js';
export {
  backgroundColorField,
  deriveThemeColor,
  resolveBackgroundColor,
  resolveStrokeColor,
  strokeColorField,
  TRANSPARENT_FILL,
  type ColorTheme,
} from './themeColors.js';
export {
  SERVICE_NAME,
  type LiveHealthResponse,
  type NotReadyHealthResponse,
  type ReadinessResponse,
  type ReadyHealthResponse,
} from './health.js';
